# packages/economy/economy/__init__.py
from __future__ import annotations

from .config import GameConfig
from .engine import calculate_weekly_wages, generate_agent_offer
from .calculator import level_up_cost, rarity_rating_cap, compute_new_overall
from .flows import (
    EconomyConfig,
    bot_match_coins,
    league_match_coins,
    league_entry_fee,
    league_match_coins_for_result,
    friendly_match_coins,
    drill_cost,
    daily_login_reward,
    simulate_casual_day,
    simulate_hardcore_day,
    simulate_days,
)
from .facility_effects import (
    FACILITY_MAX_LEVEL,
    HOSPITAL_MAX_LEVEL,
    HOSPITAL_UPGRADE_COSTS,
    academy_slot_cap,
    facility_label,
    facility_upgrade_cost,
    hospital_bed_capacity,
    hospital_recovery_multiplier,
    hospital_upgrade_cost,
    min_matches_for_next_level,
    scout_tier_cost,
    scout_tier_hours,
    training_ground_drill_xp_bonus,
    youth_academy_tier,
)

from .scouting_market import scouting_purchase_price
from .transfer_market import (
    DEFAULT_CEIL_MULT,
    DEFAULT_FLOOR_MULT,
    DEFAULT_TAX_BPS,
    fair_value_coins,
    listing_price_bounds,
    price_bounds_for_card,
    seller_net,
    tax_amount,
    validate_listing_price,
)
from .wages import (
    card_weekly_wage,
    calculate_xi_weekly_bill,
    contract_blocks_xi,
    contract_in_grace,
    payroll_outcome_after_pay,
    strike_blocks_friendly,
    strike_blocks_market,
)

__all__ = [
    "GameConfig",
    "EconomyConfig",
    "FACILITY_MAX_LEVEL",
    "HOSPITAL_MAX_LEVEL",
    "HOSPITAL_UPGRADE_COSTS",
    "calculate_weekly_wages",
    "card_weekly_wage",
    "calculate_xi_weekly_bill",
    "contract_blocks_xi",
    "contract_in_grace",
    "payroll_outcome_after_pay",
    "strike_blocks_friendly",
    "strike_blocks_market",
    "generate_agent_offer",
    "level_up_cost",
    "rarity_rating_cap",
    "compute_new_overall",
    "bot_match_coins",
    "league_match_coins",
    "league_entry_fee",
    "league_match_coins_for_result",
    "friendly_match_coins",
    "drill_cost",
    "daily_login_reward",
    "simulate_casual_day",
    "simulate_hardcore_day",
    "simulate_days",
    "facility_label",
    "facility_upgrade_cost",
    "hospital_upgrade_cost",
    "hospital_bed_capacity",
    "hospital_recovery_multiplier",
    "min_matches_for_next_level",
    "training_ground_drill_xp_bonus",
    "youth_academy_tier",
    "academy_slot_cap",
    "scout_tier_cost",
    "scout_tier_hours",
    "scouting_purchase_price",
    "DEFAULT_TAX_BPS",
    "DEFAULT_FLOOR_MULT",
    "DEFAULT_CEIL_MULT",
    "fair_value_coins",
    "tax_amount",
    "seller_net",
    "listing_price_bounds",
    "validate_listing_price",
    "price_bounds_for_card",
]
