"""manager_progression_and_xp_events

Revision ID: 056d009d68f7
Revises: 53f457f62189
Create Date: 2026-07-03 15:50:17.739814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056d009d68f7'
down_revision: Union[str, Sequence[str], None] = '53f457f62189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_xp_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'guild_id', 'source_type', 'source_id', name='uq_manager_xp_event_source')
    )
    op.create_index(op.f('ix_manager_xp_events_guild_id'), 'manager_xp_events', ['guild_id'], unique=False)
    op.create_index(op.f('ix_manager_xp_events_manager_id'), 'manager_xp_events', ['manager_id'], unique=False)
    
    with op.batch_alter_table("managers") as batch_op:
        batch_op.alter_column("reputation", new_column_name="career_xp", existing_type=sa.Integer())

    op.execute("UPDATE managers SET career_xp = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("managers") as batch_op:
        batch_op.alter_column("career_xp", new_column_name="reputation", existing_type=sa.Integer())

    op.execute("UPDATE managers SET reputation = 100")

    op.drop_index(op.f('ix_manager_xp_events_manager_id'), table_name='manager_xp_events')
    op.drop_index(op.f('ix_manager_xp_events_guild_id'), table_name='manager_xp_events')
    op.drop_table('manager_xp_events')
    # ### end Alembic commands ###
