"""add_facilities_table

Revision ID: 53f457f62189
Revises: 82052c55e274
Create Date: 2026-07-03 14:47:27.198224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f457f62189'
down_revision: Union[str, Sequence[str], None] = '82052c55e274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('facility_type', sa.Enum('stadium', 'training_pitch', 'youth_academy', 'medical_clinic', 'club_hq', name='facility_type'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'UPGRADING', 'MAX_LEVEL', name='facility_status'), nullable=False),
    sa.Column('upgrade_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upgrade_completes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'facility_type', name='uq_club_facility_type')
    )
    op.create_index(op.f('ix_facilities_club_id'), 'facilities', ['club_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_club_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
