"""add_daily_tick_runs

Revision ID: 82052c55e274
Revises: b6fa12647033
Create Date: 2026-07-03 14:44:06.766554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82052c55e274'
down_revision: Union[str, Sequence[str], None] = 'b6fa12647033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tick_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('tick_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='daily_tick_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'tick_date', name='uq_daily_tick_run_guild_date')
    )
    op.create_index(op.f('ix_daily_tick_runs_guild_id'), 'daily_tick_runs', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tick_runs_guild_id'), table_name='daily_tick_runs')
    op.drop_table('daily_tick_runs')
    # ### end Alembic commands ###
