"""add_friendly_match_robustness_tables

Revision ID: a2adf4c8596f
Revises: aeeeb8e31fc6
Create Date: 2026-07-03 10:37:52.847700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2adf4c8596f'
down_revision: Union[str, Sequence[str], None] = 'aeeeb8e31fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendly_cooldowns',
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('challenger_id', sa.String(length=64), nullable=False),
    sa.Column('opponent_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'challenger_id', 'opponent_id')
    )
    op.create_table('friendly_thread_breadcrumbs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('parent_message_id', sa.String(length=64), nullable=True),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleanup_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleanup_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleanup_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendly_thread_breadcrumbs_guild_id'), 'friendly_thread_breadcrumbs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_friendly_thread_breadcrumbs_thread_id'), 'friendly_thread_breadcrumbs', ['thread_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendly_thread_breadcrumbs_thread_id'), table_name='friendly_thread_breadcrumbs')
    op.drop_index(op.f('ix_friendly_thread_breadcrumbs_guild_id'), table_name='friendly_thread_breadcrumbs')
    op.drop_table('friendly_thread_breadcrumbs')
    op.drop_table('friendly_cooldowns')
    # ### end Alembic commands ###
