"""Add season snapshots

Revision ID: aeeeb8e31fc6
Revises: c3d4e5f6a1b2
Create Date: 2026-07-02 18:37:22.881211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeeeb8e31fc6'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('champion_club_id', sa.Uuid(), nullable=True),
    sa.Column('runner_up_club_id', sa.Uuid(), nullable=True),
    sa.Column('final_table_json', sa.JSON(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('total_goals', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['champion_club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_up_club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_snapshots_guild_id'), 'season_snapshots', ['guild_id'], unique=False)
    op.create_index(op.f('ix_season_snapshots_league_id'), 'season_snapshots', ['league_id'], unique=False)
    op.create_index(op.f('ix_season_snapshots_season_id'), 'season_snapshots', ['season_id'], unique=False)
    op.drop_index(op.f('idx_onboarding_active_sweep'), table_name='onboarding_sessions', postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.drop_index(op.f('idx_onboarding_cleanup_due'), table_name='onboarding_sessions', postgresql_where='(cleanup_after IS NOT NULL)')
    op.drop_index(op.f('uq_onboarding_active_per_user'), table_name='onboarding_sessions', postgresql_where="((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETING'::character varying])::text[]))")
    op.drop_constraint(op.f('uq_squad_gen_run_club_id'), 'squad_generation_runs', type_='unique')
    op.drop_index(op.f('ix_squad_generation_runs_club_id'), table_name='squad_generation_runs')
    op.create_index(op.f('ix_squad_generation_runs_club_id'), 'squad_generation_runs', ['club_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_generation_runs_club_id'), table_name='squad_generation_runs')
    op.create_index(op.f('ix_squad_generation_runs_club_id'), 'squad_generation_runs', ['club_id'], unique=False)
    op.create_unique_constraint(op.f('uq_squad_gen_run_club_id'), 'squad_generation_runs', ['club_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_onboarding_active_per_user'), 'onboarding_sessions', ['guild_id', 'user_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETING'::character varying])::text[]))")
    op.create_index(op.f('idx_onboarding_cleanup_due'), 'onboarding_sessions', ['cleanup_after'], unique=False, postgresql_where='(cleanup_after IS NOT NULL)')
    op.create_index(op.f('idx_onboarding_active_sweep'), 'onboarding_sessions', ['status', 'last_activity_at'], unique=False, postgresql_where="((status)::text = 'ACTIVE'::text)")
    op.drop_index(op.f('ix_season_snapshots_season_id'), table_name='season_snapshots')
    op.drop_index(op.f('ix_season_snapshots_league_id'), table_name='season_snapshots')
    op.drop_index(op.f('ix_season_snapshots_guild_id'), table_name='season_snapshots')
    op.drop_table('season_snapshots')
    # ### end Alembic commands ###
