"""add_club_transactions

Revision ID: b2cf89fb9aa0
Revises: 056d009d68f7
Create Date: 2026-07-03 16:50:14.280983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2cf89fb9aa0'
down_revision: Union[str, Sequence[str], None] = '056d009d68f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_before', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'source_type', 'source_id', name='uq_club_transaction_source')
    )
    op.create_index(op.f('ix_club_transactions_club_id'), 'club_transactions', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_transactions_guild_id'), 'club_transactions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_club_transactions_created_at'), 'club_transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_transactions_created_at'), table_name='club_transactions')
    op.drop_index(op.f('ix_club_transactions_guild_id'), table_name='club_transactions')
    op.drop_index(op.f('ix_club_transactions_club_id'), table_name='club_transactions')
    op.drop_table('club_transactions')
    # ### end Alembic commands ###
