"""add_player_conditions_and_consequences_applied_at

Revision ID: b6fa12647033
Revises: a2adf4c8596f
Create Date: 2026-07-03 14:26:21.168703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fa12647033'
down_revision: Union[str, Sequence[str], None] = 'a2adf4c8596f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('consequences_applied_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('injury_type', sa.String(length=64), nullable=True))
    op.add_column('players', sa.Column('injury_severity', sa.String(length=32), nullable=True))
    op.add_column('players', sa.Column('injury_days_remaining', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('injury_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('suspension_games_remaining', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('suspension_created_fixture_id', sa.Uuid(), nullable=True))
    op.add_column('players', sa.Column('last_match_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('players', sa.Column('last_match_rating', sa.Numeric(precision=3, scale=1), nullable=True))
    op.create_foreign_key(None, 'players', 'fixtures', ['suspension_created_fixture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'last_match_rating')
    op.drop_column('players', 'last_match_minutes')
    op.drop_column('players', 'suspension_created_fixture_id')
    op.drop_column('players', 'suspension_games_remaining')
    op.drop_column('players', 'injury_created_at')
    op.drop_column('players', 'injury_days_remaining')
    op.drop_column('players', 'injury_severity')
    op.drop_column('players', 'injury_type')
    op.drop_column('fixtures', 'consequences_applied_at')
    # ### end Alembic commands ###
