# packages/player_engine/player_engine/__init__.py
from __future__ import annotations

from .age_manager import (
    DEFAULT_LIFECYCLE,
    LifecyclePhase,
    age_from_dob,
    apply_xp_age_multiplier,
    can_renew_contract,
    dob_from_age,
    format_lifecycle_display,
    lifecycle_phase,
    lifecycle_phase_emoji,
    lifecycle_phase_label,
    xp_multiplier,
    yearly_stat_decline,
)
from .player_factory import create_player_card, roll_creation_age
from .youth_intake import generate_youth_intake_cards
from .regen_pool import generate_regen_from_retired
from .config import GameConfig
from .generated_player import GeneratedPlayer
from .potential import (
    RARITY_POT_CAPS,
    apply_dynamic_potential_boost,
    format_potential_display,
    generate_potential,
    potential_tier_label,
)
from .engine import (
    calculate_level,
    roll_dynamic_potential,
    calculate_contract_renewal_cost,
    calculate_true_ovr,
    apply_match_form,
)
from .progression_gates import (
    STAT_KEYS,
    can_allocate_skill_point,
    can_gain_stat_progression,
    can_start_evolution_track,
    detect_stat_inflation,
    evolution_reward_steps,
    evolution_track_stat_col,
    rebalance_stats_to_ovr,
    simulate_legacy_stat_drill,
    stats_from_card,
)
from .progression import (
    L_MAX,
    POINTS_PER_LEVEL,
    FUSION_DAILY_LIMIT,
    RETRO_SCALE_PCT,
    RETRO_MAX_PER_PLAYER,
    ALLOCATION_DAILY_CAP,
    MATCH_XP_DAILY_CAP,
    DRILL_PER_PLAYER_DAILY_CAP,
    ApplyXpResult,
    cumulative_xp_for_level,
    drill_xp_reward,
    fusion_xp_reward,
    level_from_xp,
    match_xp_reward,
    scale_retroactive_reward,
    simulate_apply_card_xp,
    skill_points_earned_for_level,
    xp_needed_for_level,
    xp_progress,
)
from .drill_catalog import (
    DRILL_TIERS,
    STAT_DRILLS as DRILL_CATALOG,
    VALID_DRILL_IDS,
    drill_coin_cost,
    drill_spec,
    drill_unlocked,
)
from .evolution_tracks import (
    CANCEL_FEE_COINS,
    EVOLUTION_START_COIN_MULTIPLIER,
    EVOLUTION_START_COOLDOWN_HOURS,
    EVOLUTION_START_ENERGY,
    EVOLUTION_START_FLAT,
    EVOLUTION_START_OVR_MULT,
    EVOLUTION_TRACKS,
    MAX_ACTIVE_EVOLUTIONS,
    VALID_TRACK_IDS,
    evolution_start_cost,
    evolution_unlocked,
    format_cooldown_remaining,
    track_goal,
    track_min_player_level,
)

__all__ = [
    "GameConfig",
    "DEFAULT_LIFECYCLE",
    "LifecyclePhase",
    "age_from_dob",
    "apply_xp_age_multiplier",
    "can_renew_contract",
    "create_player_card",
    "dob_from_age",
    "format_lifecycle_display",
    "lifecycle_phase",
    "lifecycle_phase_emoji",
    "lifecycle_phase_label",
    "roll_creation_age",
    "generate_youth_intake_cards",
    "generate_regen_from_retired",
    "xp_multiplier",
    "yearly_stat_decline",
    "RARITY_POT_CAPS",
    "GeneratedPlayer",
    "apply_dynamic_potential_boost",
    "format_potential_display",
    "generate_potential",
    "potential_tier_label",
    "calculate_level",
    "roll_dynamic_potential",
    "calculate_contract_renewal_cost",
    "calculate_true_ovr",
    "apply_match_form",
    "STAT_KEYS",
    "can_allocate_skill_point",
    "can_gain_stat_progression",
    "can_start_evolution_track",
    "detect_stat_inflation",
    "evolution_reward_steps",
    "evolution_track_stat_col",
    "rebalance_stats_to_ovr",
    "simulate_legacy_stat_drill",
    "stats_from_card",
    "L_MAX",
    "POINTS_PER_LEVEL",
    "FUSION_DAILY_LIMIT",
    "RETRO_SCALE_PCT",
    "RETRO_MAX_PER_PLAYER",
    "ALLOCATION_DAILY_CAP",
    "MATCH_XP_DAILY_CAP",
    "DRILL_PER_PLAYER_DAILY_CAP",
    "ApplyXpResult",
    "cumulative_xp_for_level",
    "drill_xp_reward",
    "fusion_xp_reward",
    "level_from_xp",
    "match_xp_reward",
    "scale_retroactive_reward",
    "simulate_apply_card_xp",
    "skill_points_earned_for_level",
    "xp_needed_for_level",
    "xp_progress",
    "DRILL_TIERS",
    "DRILL_CATALOG",
    "VALID_DRILL_IDS",
    "drill_coin_cost",
    "drill_spec",
    "drill_unlocked",
    "generate_player",
    "generate_squad",
    "EVOLUTION_TRACKS",
    "VALID_TRACK_IDS",
    "CANCEL_FEE_COINS",
    "MAX_ACTIVE_EVOLUTIONS",
    "EVOLUTION_START_COOLDOWN_HOURS",
    "EVOLUTION_START_ENERGY",
    "EVOLUTION_START_FLAT",
    "EVOLUTION_START_OVR_MULT",
    "EVOLUTION_START_COIN_MULTIPLIER",
    "evolution_start_cost",
    "evolution_unlocked",
    "format_cooldown_remaining",
    "track_goal",
    "track_min_player_level",
]
